name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: |
          if [ -d test ]; then
            julia -e 'using Pkg; Pkg.test()'
          else
            echo "No tests directory found. Skipping tests."
          fi

      - name: Build Docker image
        run: docker build -t uci-app .

      # Optionally, push to Docker Hub or GHCR here
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Push Docker image
      #   run: docker push uci-app