name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: julia -e 'using Pkg; Pkg.test()'

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(julia -e 'using Pkg; println(Pkg.project().version)')
          git tag -a "v$version" -m "Release version $version"
          git push origin "v$version"
